### ISSUE TITLE
Patch in snapshot label to drone PVC

### ISSUE THREAD

**Issue by lltr** [lltr/home-cluster#11]
```yaml
metadata:
  name: drone
  namespace: development
  labels:
    snapshot.home.arpa/enabled: "true"
```
